import React, { useEffect, useState } from 'react';
import { Linking, Pressable, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Button, Spacer, Typography } from '../../components/ui';
import { SparklesIcon } from '../../components/icons';
import { spacing, useTheme } from '../../theme';
import { storage } from '../../utils/storage';
import type { AIScreenProps } from '../../navigation/types';

import { useTranslation } from 'react-i18next';

const TERMS_URL = 'https://getverdance.com/terms.html';
const PRIVACY_URL = 'https://getverdance.com/privacy.html';

export function AIConsentScreen({ navigation }: AIScreenProps<'AIConsent'>) {
  const { t } = useTranslation(['ai', 'common', 'profile']);
  const { colors } = useTheme();
  const [checking, setChecking] = useState(true);

  useEffect(() => {
    storage.getAiPolicyAccepted()
      .then(accepted => {
        if (accepted) {
          navigation.replace('AIChat');
        } else {
          setChecking(false);
        }
      })
      .catch(() => setChecking(false)); // storage read failed — show consent rather than blank screen
  }, [navigation]);

  const handleAccept = async () => {
    await storage.setAiPolicyAccepted();
    navigation.replace('AIChat');
  };

  const handleDecline = () => {
    navigation.getParent()?.navigate('HomeTab');
  };

  if (checking) return null;

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top']}>
      <View style={styles.content}>
        <SparklesIcon size={48} color={colors.accent} />
        <Spacer size={spacing.lg} />

        <Typography preset="h3" align="center">{t('ai:consent.title', 'AI Chat')}</Typography>
        <Spacer size={spacing.sm} />
        <Typography preset="body" color={colors.textSecondary} align="center">
          {t('ai:consent.blurb', 'Ask questions and get instant answers with Bible verses to guide your study.')}
        </Typography>

        <Spacer size={spacing.lg} />
        <View style={[styles.card, { backgroundColor: colors.surfaceMuted, borderColor: colors.border }]}>
          <Typography preset="label" color={colors.textPrimary}>
            {t('ai:consent.dataWhatLabel', 'What we send')}
          </Typography>
          <Typography preset="caption" color={colors.textSecondary}>
            {t('ai:consent.dataWhat', 'The questions and messages you type, and any PDF or image you attach.')}
          </Typography>
          <Spacer size={spacing.sm} />
          <Typography preset="label" color={colors.textPrimary}>
            {t('ai:consent.dataWhoLabel', 'Who processes it')}
          </Typography>
          <Typography preset="caption" color={colors.textSecondary}>
            {t('ai:consent.dataWho', 'Our AI providers — OpenRouter and Anthropic (Claude) — receive it to generate responses. Please don’t share sensitive personal information.')}
          </Typography>
          <Spacer size={spacing.sm} />
          <Typography preset="caption" color={colors.textSecondary}>
            {t('ai:consent.accuracy', 'Answers are generated by AI and may not always be accurate. Verify important interpretations with your pastor or a trusted commentary.')}
          </Typography>
        </View>

        <Spacer size={spacing.md} />
        <Typography preset="caption" color={colors.textSecondary} align="center">
          {t('ai:consent.agreement', 'By continuing, you agree to our')}
        </Typography>
        <View style={styles.links}>
          <Pressable onPress={() => Linking.openURL(TERMS_URL)} hitSlop={8} style={({ pressed }) => pressed && styles.linkPressed}>
            <Typography preset="caption" color={colors.accent} style={styles.linkUnderline}>{t('profile:legal.terms', 'Terms of Service')}</Typography>
          </Pressable>
          <Typography preset="caption" color={colors.textSecondary}>·</Typography>
          <Pressable onPress={() => Linking.openURL(PRIVACY_URL)} hitSlop={8} style={({ pressed }) => pressed && styles.linkPressed}>
            <Typography preset="caption" color={colors.accent} style={styles.linkUnderline}>{t('profile:legal.privacy', 'Privacy Policy')}</Typography>
          </Pressable>
        </View>

        <Spacer size={spacing.xxxl} />

        <Button label={t('common:actions.continue', 'Accept & Continue')} variant="primary" fullWidth onPress={handleAccept} />
        <Spacer size={spacing.sm} />
        <Button label={t('common:actions.cancel', 'Decline')} variant="ghost" fullWidth onPress={handleDecline} />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  },
  card: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 12,
    padding: spacing.md,
    gap: 2,
  },
  links: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  linkUnderline: { textDecorationLine: 'underline' },
  linkPressed: { opacity: 0.7 },
});
